services:
  - type: web
    name: crop-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile

  - type: web
    name: crop-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://shindesiddhant415_db_user:siddhant415@crop0.cpijdjj.mongodb.net/cropdb?retryWrites=true&w=majority

      - key: ML_URL
        value: https://crop-ml.onrender.com

  - type: web
    name: crop-ml
    env: docker
    dockerfilePath: ./ml-model/Dockerfile

